#!/usr/bin/env ruby
# frozen_string_literal: true

require "sora"
require "optparse"

opt = OptionParser.new

params = { port: 8080, document_root: File.expand_path("../www", __dir__) }

opt.on("-p [PORT]", "--port [PORT]") { |v| params[:port] = v.to_i }

opt.parse!(ARGV)

Sora.server(**params)
